'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace cl.manager.api
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ProductosSoap", [Namespace]:="http://manager.cl/productos/")>  _
    Partial Public Class Productos
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultaProdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProductosConInfoFinancieraOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultaListaPrecOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultaPrecioStockOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            'Me.Url = Global.WMS_Favatex.My.MySettings.Default.WMS_Favatex_swProductos_Productos
            'If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
            '    Me.UseDefaultCredentials = True
            '    Me.useDefaultCredentialsSetExplicitly = False
            'Else
            '    Me.useDefaultCredentialsSetExplicitly = True
            'End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultaProdCompleted As ConsultaProdCompletedEventHandler
        
        '''<remarks/>
        Public Event ProductosConInfoFinancieraCompleted As ProductosConInfoFinancieraCompletedEventHandler
        
        '''<remarks/>
        Public Event consultaListaPrecCompleted As consultaListaPrecCompletedEventHandler
        
        '''<remarks/>
        Public Event consultaPrecioStockCompleted As consultaPrecioStockCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://manager.cl/productos/ConsultaProd", RequestNamespace:="http://manager.cl/productos/", ResponseNamespace:="http://manager.cl/productos/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultaProd(ByVal rutEmpresa As String, ByVal token As String) As consultaProd()
            Dim results() As Object = Me.Invoke("ConsultaProd", New Object() {rutEmpresa, token})
            Return CType(results(0),consultaProd())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultaProdAsync(ByVal rutEmpresa As String, ByVal token As String)
            Me.ConsultaProdAsync(rutEmpresa, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultaProdAsync(ByVal rutEmpresa As String, ByVal token As String, ByVal userState As Object)
            If (Me.ConsultaProdOperationCompleted Is Nothing) Then
                Me.ConsultaProdOperationCompleted = AddressOf Me.OnConsultaProdOperationCompleted
            End If
            Me.InvokeAsync("ConsultaProd", New Object() {rutEmpresa, token}, Me.ConsultaProdOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultaProdOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultaProdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultaProdCompleted(Me, New ConsultaProdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://manager.cl/productos/ProductosConInfoFinanciera", RequestNamespace:="http://manager.cl/productos/", ResponseNamespace:="http://manager.cl/productos/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProductosConInfoFinanciera(ByVal rutEmpresa As String, ByVal token As String) As transaccionResult
            Dim results() As Object = Me.Invoke("ProductosConInfoFinanciera", New Object() {rutEmpresa, token})
            Return CType(results(0),transaccionResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProductosConInfoFinancieraAsync(ByVal rutEmpresa As String, ByVal token As String)
            Me.ProductosConInfoFinancieraAsync(rutEmpresa, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProductosConInfoFinancieraAsync(ByVal rutEmpresa As String, ByVal token As String, ByVal userState As Object)
            If (Me.ProductosConInfoFinancieraOperationCompleted Is Nothing) Then
                Me.ProductosConInfoFinancieraOperationCompleted = AddressOf Me.OnProductosConInfoFinancieraOperationCompleted
            End If
            Me.InvokeAsync("ProductosConInfoFinanciera", New Object() {rutEmpresa, token}, Me.ProductosConInfoFinancieraOperationCompleted, userState)
        End Sub
        
        Private Sub OnProductosConInfoFinancieraOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProductosConInfoFinancieraCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProductosConInfoFinancieraCompleted(Me, New ProductosConInfoFinancieraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://manager.cl/productos/consultaListaPrec", RequestNamespace:="http://manager.cl/productos/", ResponseNamespace:="http://manager.cl/productos/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultaListaPrec(ByVal rutEmpresa As String, ByVal token As String) As ListaDePrecios()
            Dim results() As Object = Me.Invoke("consultaListaPrec", New Object() {rutEmpresa, token})
            Return CType(results(0),ListaDePrecios())
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultaListaPrecAsync(ByVal rutEmpresa As String, ByVal token As String)
            Me.consultaListaPrecAsync(rutEmpresa, token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultaListaPrecAsync(ByVal rutEmpresa As String, ByVal token As String, ByVal userState As Object)
            If (Me.consultaListaPrecOperationCompleted Is Nothing) Then
                Me.consultaListaPrecOperationCompleted = AddressOf Me.OnconsultaListaPrecOperationCompleted
            End If
            Me.InvokeAsync("consultaListaPrec", New Object() {rutEmpresa, token}, Me.consultaListaPrecOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultaListaPrecOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultaListaPrecCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultaListaPrecCompleted(Me, New consultaListaPrecCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://manager.cl/productos/consultaPrecioStock", RequestNamespace:="http://manager.cl/productos/", ResponseNamespace:="http://manager.cl/productos/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultaPrecioStock(ByVal rutEmpresa As String, ByVal token As String, ByVal pm_codigo As String) As ProductoPrecioStock
            Dim results() As Object = Me.Invoke("consultaPrecioStock", New Object() {rutEmpresa, token, pm_codigo})
            Return CType(results(0),ProductoPrecioStock)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultaPrecioStockAsync(ByVal rutEmpresa As String, ByVal token As String, ByVal pm_codigo As String)
            Me.consultaPrecioStockAsync(rutEmpresa, token, pm_codigo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultaPrecioStockAsync(ByVal rutEmpresa As String, ByVal token As String, ByVal pm_codigo As String, ByVal userState As Object)
            If (Me.consultaPrecioStockOperationCompleted Is Nothing) Then
                Me.consultaPrecioStockOperationCompleted = AddressOf Me.OnconsultaPrecioStockOperationCompleted
            End If
            Me.InvokeAsync("consultaPrecioStock", New Object() {rutEmpresa, token, pm_codigo}, Me.consultaPrecioStockOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultaPrecioStockOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultaPrecioStockCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultaPrecioStockCompleted(Me, New consultaPrecioStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://manager.cl/productos/")>  _
    Partial Public Class consultaProd
        
        Private codigoField As String
        
        Private nombreField As String
        
        Private obsField As String
        
        Private factorConversionField As String
        
        Private taxPjeField As String
        
        Private taxTipoField As String
        
        Private unidMedField As String
        
        Private categDesctoField As String
        
        Private categDesctoFactorPrecioField As Double
        
        Private categDesctoFactorComisionField As Double
        
        '''<remarks/>
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property obs() As String
            Get
                Return Me.obsField
            End Get
            Set
                Me.obsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property factorConversion() As String
            Get
                Return Me.factorConversionField
            End Get
            Set
                Me.factorConversionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property taxPje() As String
            Get
                Return Me.taxPjeField
            End Get
            Set
                Me.taxPjeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property taxTipo() As String
            Get
                Return Me.taxTipoField
            End Get
            Set
                Me.taxTipoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property unidMed() As String
            Get
                Return Me.unidMedField
            End Get
            Set
                Me.unidMedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property categDescto() As String
            Get
                Return Me.categDesctoField
            End Get
            Set
                Me.categDesctoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property categDesctoFactorPrecio() As Double
            Get
                Return Me.categDesctoFactorPrecioField
            End Get
            Set
                Me.categDesctoFactorPrecioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property categDesctoFactorComision() As Double
            Get
                Return Me.categDesctoFactorComisionField
            End Get
            Set
                Me.categDesctoFactorComisionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://manager.cl/productos/")>  _
    Partial Public Class descuentoVolumen
        
        Private minField As Integer
        
        Private maxField As Integer
        
        Private porcDesctoField As Double
        
        '''<remarks/>
        Public Property min() As Integer
            Get
                Return Me.minField
            End Get
            Set
                Me.minField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property max() As Integer
            Get
                Return Me.maxField
            End Get
            Set
                Me.maxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property porcDescto() As Double
            Get
                Return Me.porcDesctoField
            End Get
            Set
                Me.porcDesctoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://manager.cl/productos/")>  _
    Partial Public Class RegistroStockFisico
        
        Private bodegaField As String
        
        Private stockFisicoField As Integer
        
        '''<remarks/>
        Public Property bodega() As String
            Get
                Return Me.bodegaField
            End Get
            Set
                Me.bodegaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property stockFisico() As Integer
            Get
                Return Me.stockFisicoField
            End Get
            Set
                Me.stockFisicoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://manager.cl/productos/")>  _
    Partial Public Class ProductoPrecioStock
        
        Private stockFisicoField() As RegistroStockFisico
        
        Private desctoVolumenField() As descuentoVolumen
        
        Private codigoField As String
        
        Private precioUnitarioField As Integer
        
        '''<remarks/>
        Public Property stockFisico() As RegistroStockFisico()
            Get
                Return Me.stockFisicoField
            End Get
            Set
                Me.stockFisicoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property desctoVolumen() As descuentoVolumen()
            Get
                Return Me.desctoVolumenField
            End Get
            Set
                Me.desctoVolumenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property precioUnitario() As Integer
            Get
                Return Me.precioUnitarioField
            End Get
            Set
                Me.precioUnitarioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://manager.cl/productos/")>  _
    Partial Public Class prodEnListadePrecios
        
        Private idProductoField As String
        
        Private precioListaField As Integer
        
        '''<remarks/>
        Public Property idProducto() As String
            Get
                Return Me.idProductoField
            End Get
            Set
                Me.idProductoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property precioLista() As Integer
            Get
                Return Me.precioListaField
            End Get
            Set
                Me.precioListaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://manager.cl/productos/")>  _
    Partial Public Class ListaDePrecios
        
        Private listaProdField() As prodEnListadePrecios
        
        Private nombreListaPrecioField As String
        
        Private idMonedaField As String
        
        '''<remarks/>
        Public Property ListaProd() As prodEnListadePrecios()
            Get
                Return Me.listaProdField
            End Get
            Set
                Me.listaProdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nombreListaPrecio() As String
            Get
                Return Me.nombreListaPrecioField
            End Get
            Set
                Me.nombreListaPrecioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idMoneda() As String
            Get
                Return Me.idMonedaField
            End Get
            Set
                Me.idMonedaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://manager.cl/productos/")>  _
    Partial Public Class transaccionResult
        
        Private mensajeField As String
        
        Private errorField As Integer
        
        Private okField As Boolean
        
        Private dataField As String
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Error]() As Integer
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ok() As Boolean
            Get
                Return Me.okField
            End Get
            Set
                Me.okField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Data() As String
            Get
                Return Me.dataField
            End Get
            Set
                Me.dataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub ConsultaProdCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultaProdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultaProdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As consultaProd()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),consultaProd())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub ProductosConInfoFinancieraCompletedEventHandler(ByVal sender As Object, ByVal e As ProductosConInfoFinancieraCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProductosConInfoFinancieraCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As transaccionResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),transaccionResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub consultaListaPrecCompletedEventHandler(ByVal sender As Object, ByVal e As consultaListaPrecCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultaListaPrecCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ListaDePrecios()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ListaDePrecios())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub consultaPrecioStockCompletedEventHandler(ByVal sender As Object, ByVal e As consultaPrecioStockCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultaPrecioStockCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProductoPrecioStock
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProductoPrecioStock)
            End Get
        End Property
    End Class
End Namespace
